---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: check for SSH agent to be available and have a key loaded
      command: "ssh-add -L"
      register: ssh_check
      failed_when: ssh_check.rc > 0
      changed_when: ssh_check.rc != 0

    - name: Install homesick repositories
      git:
        repo: "{{ item.value }}"
        dest: "{{ ansible_user_dir }}/.homesick/repos/{{ item.key }}"
        accept_hostkey: true
      with_dict: "{{ homesick_repos }}"
      loop_control:
        label: "{{ item.key }} -> {{ item.value }}"

    - name: Link homeshick repositories with homeshick
      command:
        argv: ["/opt/homebrew/bin/homeshick", "link", "{{ item.key }}"]
      with_dict: "{{ homesick_repos }}"
      register: homeshick_link
      changed_when: homeshick_link.stdout_lines | length > 0

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
